//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public int LogID { get; set; }
        public System.DateTime EventDate { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string EmployeeNameSnapshot { get; set; }
        public string EventType { get; set; }
        public string EntityName { get; set; }
        public int EntityID { get; set; }
        public string Description { get; set; }
        public string Details { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
