//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivedPurchases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArchivedPurchases()
        {
            this.ArchivedPurchaseItems = new HashSet<ArchivedPurchaseItems>();
        }
    
        public int ArchiveID { get; set; }
        public int PurchaseID { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime ClosedAt { get; set; }
        public int EmployeeID { get; set; }
        public string EmployeeFullName { get; set; }
        public int SupplierID { get; set; }
        public string SupplierName { get; set; }
        public decimal TotalPrice { get; set; }
        public Nullable<System.DateTime> ArchivedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchivedPurchaseItems> ArchivedPurchaseItems { get; set; }
    }
}
