//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivedOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArchivedOrders()
        {
            this.ArchivedOrderItems = new HashSet<ArchivedOrderItems>();
        }
    
        public int ArchiveID { get; set; }
        public int OrderID { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime ClosedAt { get; set; }
        public int EmployeeID { get; set; }
        public string EmployeeFullName { get; set; }
        public decimal TotalPrice { get; set; }
        public Nullable<System.DateTime> ArchivedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchivedOrderItems> ArchivedOrderItems { get; set; }
    }
}
