//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseItems
    {
        public int PurchaseID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> PriceID { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual ProductPrices ProductPrices { get; set; }
        public virtual Products Products { get; set; }
        public virtual Purchases Purchases { get; set; }
    }
}
