//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RestaurantEntities : DbContext
    {
        public RestaurantEntities()
            : base("name=RestaurantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityLog> ActivityLog { get; set; }
        public virtual DbSet<ArchivedOrderItems> ArchivedOrderItems { get; set; }
        public virtual DbSet<ArchivedOrders> ArchivedOrders { get; set; }
        public virtual DbSet<ArchivedPurchaseItems> ArchivedPurchaseItems { get; set; }
        public virtual DbSet<ArchivedPurchases> ArchivedPurchases { get; set; }
        public virtual DbSet<DishCategories> DishCategories { get; set; }
        public virtual DbSet<Dishes> Dishes { get; set; }
        public virtual DbSet<DishProducts> DishProducts { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<OrderItems> OrderItems { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Permissions> Permissions { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<ProdCategories> ProdCategories { get; set; }
        public virtual DbSet<ProductPrices> ProductPrices { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<PurchaseItems> PurchaseItems { get; set; }
        public virtual DbSet<Purchases> Purchases { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
        public virtual DbSet<vw_AllPermissions> vw_AllPermissions { get; set; }
        public virtual DbSet<vw_OrderDetails> vw_OrderDetails { get; set; }
        public virtual DbSet<vw_PositionPermissions> vw_PositionPermissions { get; set; }
        public virtual DbSet<vw_ProductsByCategory> vw_ProductsByCategory { get; set; }
        public virtual DbSet<vw_PurchaseDetails> vw_PurchaseDetails { get; set; }
    
        [DbFunction("RestaurantEntities", "GetExpensesByMonth")]
        public virtual IQueryable<GetExpensesByMonth_Result> GetExpensesByMonth(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> supplierID)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var supplierIDParameter = supplierID.HasValue ?
                new ObjectParameter("SupplierID", supplierID) :
                new ObjectParameter("SupplierID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetExpensesByMonth_Result>("[RestaurantEntities].[GetExpensesByMonth](@StartDate, @EndDate, @SupplierID)", startDateParameter, endDateParameter, supplierIDParameter);
        }
    
        [DbFunction("RestaurantEntities", "GetOperationsList")]
        public virtual IQueryable<GetOperationsList_Result> GetOperationsList(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, string reportType, Nullable<int> employeeID, Nullable<int> supplierID)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var reportTypeParameter = reportType != null ?
                new ObjectParameter("ReportType", reportType) :
                new ObjectParameter("ReportType", typeof(string));
    
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(int));
    
            var supplierIDParameter = supplierID.HasValue ?
                new ObjectParameter("SupplierID", supplierID) :
                new ObjectParameter("SupplierID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetOperationsList_Result>("[RestaurantEntities].[GetOperationsList](@StartDate, @EndDate, @ReportType, @EmployeeID, @SupplierID)", startDateParameter, endDateParameter, reportTypeParameter, employeeIDParameter, supplierIDParameter);
        }
    
        [DbFunction("RestaurantEntities", "GetProfitByPeriod")]
        public virtual IQueryable<GetProfitByPeriod_Result> GetProfitByPeriod(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> employeeID, Nullable<int> supplierID)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(int));
    
            var supplierIDParameter = supplierID.HasValue ?
                new ObjectParameter("SupplierID", supplierID) :
                new ObjectParameter("SupplierID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetProfitByPeriod_Result>("[RestaurantEntities].[GetProfitByPeriod](@StartDate, @EndDate, @EmployeeID, @SupplierID)", startDateParameter, endDateParameter, employeeIDParameter, supplierIDParameter);
        }
    
        [DbFunction("RestaurantEntities", "GetRequiredProductsForActiveOrders")]
        public virtual IQueryable<GetRequiredProductsForActiveOrders_Result> GetRequiredProductsForActiveOrders()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetRequiredProductsForActiveOrders_Result>("[RestaurantEntities].[GetRequiredProductsForActiveOrders]()");
        }
    
        [DbFunction("RestaurantEntities", "GetRevenueByMonth")]
        public virtual IQueryable<GetRevenueByMonth_Result> GetRevenueByMonth(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> employeeID)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetRevenueByMonth_Result>("[RestaurantEntities].[GetRevenueByMonth](@StartDate, @EndDate, @EmployeeID)", startDateParameter, endDateParameter, employeeIDParameter);
        }
    
        public virtual ObjectResult<sp_LoginUser_Result> sp_LoginUser(string login, string passwordHash)
        {
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var passwordHashParameter = passwordHash != null ?
                new ObjectParameter("PasswordHash", passwordHash) :
                new ObjectParameter("PasswordHash", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LoginUser_Result>("sp_LoginUser", loginParameter, passwordHashParameter);
        }
    
        public virtual ObjectResult<sp_RegisterUser_Result> sp_RegisterUser(string lName, string fName, string mName, string login, string inviteCodeHash, string passwordHash)
        {
            var lNameParameter = lName != null ?
                new ObjectParameter("LName", lName) :
                new ObjectParameter("LName", typeof(string));
    
            var fNameParameter = fName != null ?
                new ObjectParameter("FName", fName) :
                new ObjectParameter("FName", typeof(string));
    
            var mNameParameter = mName != null ?
                new ObjectParameter("MName", mName) :
                new ObjectParameter("MName", typeof(string));
    
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var inviteCodeHashParameter = inviteCodeHash != null ?
                new ObjectParameter("InviteCodeHash", inviteCodeHash) :
                new ObjectParameter("InviteCodeHash", typeof(string));
    
            var passwordHashParameter = passwordHash != null ?
                new ObjectParameter("PasswordHash", passwordHash) :
                new ObjectParameter("PasswordHash", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RegisterUser_Result>("sp_RegisterUser", lNameParameter, fNameParameter, mNameParameter, loginParameter, inviteCodeHashParameter, passwordHashParameter);
        }
    
        public virtual int sp_UpdateWarehouseOnDelivery(Nullable<int> purchaseID)
        {
            var purchaseIDParameter = purchaseID.HasValue ?
                new ObjectParameter("PurchaseID", purchaseID) :
                new ObjectParameter("PurchaseID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateWarehouseOnDelivery", purchaseIDParameter);
        }
    
        public virtual int sp_UpdateWarehouseOnOrderCompletion(Nullable<int> orderID)
        {
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateWarehouseOnOrderCompletion", orderIDParameter);
        }
    }
}
