//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AllPermissions
    {
        public int PositionID { get; set; }
        public string PositionName { get; set; }
        public int PermissionID { get; set; }
        public string PermissionName { get; set; }
        public Nullable<bool> HasPermission { get; set; }
    }
}
