//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_OrderDetails
    {
        public int OrderID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> ClosedAt { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> TotalOrderPrice { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string EmployeeFullName { get; set; }
        public int DishID { get; set; }
        public string DishName { get; set; }
        public Nullable<decimal> DishBasePrice { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<decimal> ItemTotalPrice { get; set; }
    }
}
