//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PurchaseDetails
    {
        public int PurchaseID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> ClosedAt { get; set; }
        public string PurchaseStatus { get; set; }
        public Nullable<decimal> TotalPurchasePrice { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string EmployeeFullName { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string SupplierName { get; set; }
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public decimal Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<decimal> ItemTotalPrice { get; set; }
    }
}
